# Generated by Django 2.1.5 on 2019-03-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190312_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastpractice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='lastpractice',
            name='hour',
            field=models.CharField(choices=[('1', '1 hour'), ('2', '2 hours'), ('3', '3 hours')], default='1', max_length=1),
        ),
    ]
