# Generated by Django 2.1.5 on 2019-03-13 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190313_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Last Practice Date')),
                ('hour', models.CharField(choices=[('1', '1 hour'), ('2', '2 hours'), ('3', '3 hours')], default='1', max_length=1)),
                ('guitar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Guitar')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RemoveField(
            model_name='lastpractice',
            name='guitar',
        ),
        migrations.DeleteModel(
            name='LastPractice',
        ),
    ]
