# Generated by Django 2.1.5 on 2019-03-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20190313_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='guitar',
            name='amps',
            field=models.ManyToManyField(to='main_app.Amp'),
        ),
    ]
